# Use the official .NET SDK image to build the app
FROM ://microsoft.com AS build
WORKDIR /src
COPY ["SisigNiBessWebApiAdmin.csproj", "./"]
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app

# Use the ASP.NET runtime image for the final stage
FROM ://microsoft.com
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "SisigNiBessWebApiAdmin.dll"]
